### ISSUE TITLE
Add Scheduling to the Promotional Banner

### ISSUE THREAD

**Issue by zorexsalvo** [pythonph/pyconapac-2025#11]
Implement a scheduling feature for the promotional banner on the website. This will allow the banner to automatically update based on the event timeline or promotional content schedule.

![image](https://github.com/user-attachments/assets/d4ccc089-066f-4fd5-a616-6aa3998dd488)

**Comment by vamc-k** [comment]
@zorexsalvo Few points to confirm regarding this issue.

 - Can we schedule more than 1 active banner at same time. If yes whats the limit to render on page.

**Comment by zorexsalvo** [comment]
Hi @vamc-k good points!

Now that I think about it, I believe it’s best not to support multiple promo banners (supporting multiple will just add complexity to the site and theres not enough use case to utilize it). We just need to ensure that the current banner does not display after the given deadline.

**Comment by vamc-k** [comment]
> Hi @vamc-k good points!
> 
> Now that I think about it, I believe it’s best not to support multiple promo banners (supporting multiple will just add complexity to the site and theres not enough use case to utilize it). We just need to ensure that the current banner does not display after the given deadline.

Got it. I'll make changes and create PR for the same.
