### ISSUE TITLE
Add a Get Tickets CTA 

### ISSUE THREAD

**Issue by zorexsalvo** [pythonph/pyconapac-2025#13]
To be implemented in the Hero and Footer sections

Note:
There is already a field in the db for this. See [models.py#L36C3-L36C46](https://github.com/pythonph/pyconapac-2025/blob/08d23ecaee6020daaa33cf336417720005a76e20/pyconph/home/models.py#L36C3-L36C46)

That was repurposed to be used as a Call-For-Volunteers btn.

![image](https://github.com/user-attachments/assets/93667181-9788-41a8-b192-a267b52498c3)
![image](https://github.com/user-attachments/assets/aaf32397-f7be-4bd5-9526-84f55be64d47)

**Comment by vamc-k** [comment]
@zorexsalvo 
Here we need to add below 2 elements in the page right
 - Call for Volunteers button (Required to add field volunteer_link in backend ?)
 - CTA for "Get tickets" & "Become a Sponsor"

**Comment by vamc-k** [comment]
> @zorexsalvo Here we need to add below 2 elements in the page right
> 
> * "Get Tickets" button
> * CTA for "Get tickets" & "Become a Sponsor"
> 
> For "Call-for-volunteers" button:
> 
> * Does it required to add field volunteer_link in backend ?

Assuming we are not going to open volunteers form anymore, so no need for "volunteers_link" field in backend. Am I right @zorexsalvo

**Comment by zorexsalvo** [comment]
> > @zorexsalvo Here we need to add below 2 elements in the page right
> > 
> > * "Get Tickets" button
> > * CTA for "Get tickets" & "Become a Sponsor"
> > 
> > For "Call-for-volunteers" button:
> > 
> > * Does it required to add field volunteer_link in backend ?
> 
> Assuming we are not going to open volunteers form anymore, so no need for "volunteers_link" field in backend. Am I right @zorexsalvo

Yes, you are right. No need to add the volunteers_link anymore @vamc-k
