### ISSUE TITLE
Add the navbar

### ISSUE THREAD

**Issue by zorexsalvo** [pythonph/pyconapac-2025#14]
We need to implement a responsive navbar for better navigation across the site.

![image](https://github.com/user-attachments/assets/4a99378d-3ff6-49ab-94bc-1f3afb1dafb6)

**Comment by Kands221** [comment]
How do I assign myself to this po. Thank you!

**Comment by zorexsalvo** [comment]
> How do I assign myself to this po. Thank you!

Hi @Kands221 apologies for the late reply as I was on a trip, but I just assigned this issue to you.
Reviewing the PR now. Thanks!
